[79] add merge driver, refactor
nestauk/daps_utils pull request #91
Opened 2021-07-15 15:54 UTC by jooh

closes #79

I also took the opportunity to clean up calver-init a bit.

2021-07-20 11:49 UTC, jaklinger requested changes
Hey - thanks for this! Just a minor addition was required to get in working on my side, a weird case of the wrong "`echo`" being used in the calver script which can be resolved by adding a shebang to the pre-commit script.

I *think* it all looks good now, I set up a dummy repo and a conflict was averted by the right strategy. It's quite hard to think of edge-cases, so let's keep an eye on it!

Regarding next steps, I guess both this repo and `ojd_daps` will require a `.gitattributes` adding or editing (`ojd_daps` has a `.gitattriutes` already) and also the `.gitconfig`.

Thanks again!

2021-07-20 11:49 UTC, jaklinger commented on scripts/calver-init
> +    _AddHeader ".githooks/pre-commit"
When testing, I found that the following must have been missing (not sure why it even works without it...) to ensure that the correct shell is used. In my case, without it the precommit hook was using the wrong `echo` leading to `echo -n` printing the `-n` character (weird!) (as seen in [this issue](https://stackoverflow.com/questions/11193466/echo-n-prints-n))

```suggestion
    echo '#!/usr/bin/env bash' >> .githooks/pre-commit
    _AddHeader ".githooks/pre-commit"
```

2021-07-20 15:06 UTC, jooh commented
Thanks for feedback. If this is good to merge, I can then use the updated `calver-init` to update daps_utils and ojd_daps.

2021-07-20 15:06 UTC, jooh commented
(or maybe better to bake the application into the same PR?)

2021-07-20 20:39 UTC, jooh commented
Anyway, on further tests this is *not* ready to merge and those shebang insertions are creating multiple shebangs. So will work more on this tomorrow.

2021-07-26 10:55 UTC, jooh commented
Ok, should work now. I have added the application to the repo as well, so the merge driver will be there once you run `install.sh`.

2021-07-27 10:28 UTC, jaklinger approved these changes
tldr: Good to merge

What I did:

* created a new test repo `test`
* used the new `calver-init`
* commented out `incrementVersion`
* Created two branches with identical conflicting changes in a file called `README` and `test/VERSION`
* On merge, there was a conflict in `README` as expected, but no conflict in `test/VERSION`, thanks to the merge driver

In short, works out-of-the-box, thanks for this

2021-07-27 10:32 UTC, merged